name: Update Contributors

on:
  push:
    branches:
      - main

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Contributors List
        run: |
          echo "<!-- START: CONTRIBUTORS -->" > README.md
          curl -s "https://api.github.com/orgs/MelvanTeam/members" | jq -r '.[].login' | awk '{print "- [" $0 "](https://github.com/" $0 ")"}' >> README.md
          echo "<!-- END: CONTRIBUTORS -->" >> README.md

      - name: Commit and Push Changes
        run: |
          git config user.name "CoeF"
          git config user.email "xnotforyou@gmail.com"
          git add README.md
          git commit -m "Update contributors list"
          git push

