name: Update Contributors

on:
  push:
    branches:
      - main

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Contributors List
        run: |
          # Buat file sementara untuk menyimpan daftar anggota
          echo "<!-- START: CONTRIBUTORS -->" > profile/contributors.md
          curl -s "https://api.github.com/orgs/MelvanTeam/members" | jq -r '.[].login' | awk '{print "- [" $0 "](https://github.com/" $0 ")"}' >> profile/contributors.md
          echo "<!-- END: CONTRIBUTORS -->" >> profile/contributors.md
          
          # Gabungkan file sementara dengan Readme.md yang sudah ada
          cat profile/contributors.md >> profile/README.md
          
          # Hapus file sementara
          rm profile/contributors.md

      - name: Commit and Push Changes
        run: |
          git config user.name "CoeF"
          git config user.email "xnotforyou@gmail.com"
          git add profile/README.md
          git commit -m "Update contributors list"
          git push

